version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "python"
        versions: ["2.*", "3.0", "3.1", "3.2", "3.3", "3.4"]
      - dependency-name: "Flask"
        versions: ["2.*"]
      - dependency-name: "pyshorteners"
